<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Gateway.Core\Gateway.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TitaniumAS.Opc.Client.NetCore" Version="1.0.2.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
